mythril/ipc/client.py

This adds tracing functionality to ipc. Probably I will add the remaining functions (that are not currently used) with a future pull request, but this one was more important as it is actually used.

add ipc function for tracing

---

README.md
myth
mythril/ether/contractstorage.py
mythril/ether/util.py

This allows you to use 
```
./myth --rpchost "mainnet.infura.io/{INFURA_KEY}" --rpcport "443" --rpctls="True" -g ./graphlol.html -a "0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208"
```
or any other node which requires https to connect to.
I'm not sure why I'm being partially credited for the README.md update commit, but I spent a bit of time trying to fix it without success.

Tls option

---

mythril/ether/ethcontract.py

Additional filtering in search.

Add NOT logical statement to the match method of the ETHContract class

---

mythril/analysis/callgraph.py

Big nodes were clogging up the screen space. Now they start collapsed and you can expand them! 😄 
http://www.giphy.com/gifs/3o6fJ74OeeWyUPFGVy

Add ability to collapse big nodes in the graph

---

mythril/ether/util.py

Mythril `compile_solidity`:
* doesn't use its own `solc_binary` argument
* doesn't offer NIX signal tracking if `solc` has internal fatal issues,
such as SIGSEGV
This commit adds a more verbose message for a fatal error in `solc` and uses the `solc_binary` argument. It may be worthwhile to set the default argument for `solc_binary` in the function declaration.
*Note:* My system has a strange issue in which my `solc` will segfault when run *only* from the Mythril subprocess. Running the same code as below in the Python repl. It wasn't clear what the problem Mythril was running into was, as it just displayed a blank string on the segfault. This helps others debug this same issue, and fixes a bug in which `solc_binary` was not passed in.
Tested on Python 3.6.3, Arch Linux x64 4.14.5-1.

Add retcode error checking, solc_binary argument

---

mythril/analysis/modules/weak_random.py

Added second check: `block.blockhash()` dependent Ether transfers. The following patterns are detected:
- `block.blockhash(block.number)`
- `block.blockhash(block.number - N)`;
- `block.blockhash(block.number - storage_N)`
- `block.blockhash(storage_N)`
The last check has informational severity since it is quite common to compute blockhash of a value that is stored in storage. That value is usually `block.number` which is perfectly fine unless there is no check that the resulting `bytes32` value is zero (see the notice http://solidity.readthedocs.io/en/develop/units-and-global-variables.html). We could add a new constraint like `blockhash_block_storage_0 == 0` but I could not find any reference to this symbolic variable in the stack or memory.

[weak random] add blockhash dependent calls detection

---

README.md

python3, pip3 & mkdir ~/.mythril

Installation commands

---

.gitignore
myth

➜  mythril git:(master) myth -a 0x8cdaf0cd259887258bc13a92c0a6da92698644c0 --storage 0,10 --rpcport 7545
0x0: 0x0f
0x1: 0x5a615ff00000000000000000000000000000429f
0x2: 0x74657374310000000000000000000000
0x3: 0x7465737431323336000000000000000000000000000000000000000000000000
0x4: 0x6c65747320737472696e6720736f6d657468696e67000000000000000000002a
0x5: 0x00
0x6: 0x00
0x7: 0x02
0x8: 0x02
0x9: 0x00
➜  mythril git:(master) myth -a 0x8cdaf0cd259887258bc13a92c0a6da92698644c0 --storage 7,10,array --rpcport 7545
0xa66cc928b5edb82af9bd49922954155ab7b0942694bea4ce44661d9a8736c688: 0x1f40
0xa66cc928b5edb82af9bd49922954155ab7b0942694bea4ce44661d9a8736c689: 0x2328
0xa66cc928b5edb82af9bd49922954155ab7b0942694bea4ce44661d9a8736c68a: 0x00
0xa66cc928b5edb82af9bd49922954155ab7b0942694bea4ce44661d9a8736c68b: …

Storage can read more elements than one and also arrays

---

all_tests.sh
myth
tests/cmline_test.py

Use `python3` explicitly to reduce conflict

---

.editorconfig
myth
mythril/analysis/report.py

I will put some comments on changes

Myth refactoring

---

README.md
mythril/support/truffle.py
static/sample_report.md
tests/cmd_line_test.py
tests/testdata/outputs_expected/ether_send.sol.json
tests/testdata/outputs_expected/ether_send.sol.markdown
tests/testdata/outputs_expected/ether_send.sol.text
tests/testdata/outputs_expected/metacoin.sol.json
tests/testdata/outputs_expected/metacoin.sol.markdown
tests/testdata/outputs_expected/metacoin.sol.text
tests/testdata/outputs_expected/multi_contracts.sol.json
tests/testdata/outputs_expected/multi_contracts.sol.markdown
tests/testdata/outputs_expected/multi_contracts.sol.text
tests/testdata/outputs_expected/overflow.sol.json
tests/testdata/outputs_expected/overflow.sol.markdown
tests/testdata/outputs_expected/overflow.sol.text
tests/testdata/outputs_expected/rubixi.sol.json
tests/testdata/outputs_expected/rubixi.sol.markdown
tests/testdata/outputs_expected/rubixi.sol.text
tests/testdata/outputs_expected/underflow.sol.json
tests/testdata/outputs_expected/underflow.sol.markdown
tests/testdata/outputs_expected/underflow.sol.text
tests/testdata/outputs_expected/weak_random.sol.json
tests/testdata/outputs_expected/weak_random.sol.markdown
tests/testdata/outputs_expected/weak_random.sol.text

wrap all functions in back ticks #108

wrap all functions in back ticks #108

---

mythril/analysis/modules/integer.py

This pr implements roughly three things:
- Remove nesting from integer overflow detection method
- Add some comments
- Implement a check if an overflowed value can be influenced by a user/attacker, if not then the case is benign

Check for benign cases in integer overflows

---

myth
mythril/analysis/callgraph.py
mythril/analysis/templates/graph.html
requirements.txt

This replicates the previous behavior with more ability to modify options.
Fixes #123

Migrate to Jinja2 templating

---

mythril/analysis/modules/integer.py

I made a little mistake in the maximum possible value for an integer. This pr fixes the problem

Change max unsigned integer size

---

mythril/analysis/modules/integer.py

This fixes issue #145, The problem was caused by the following situation:
expression = 4 + calldata_Roles_32 + 4
some later jumpi condition: ULE(32, calldata_Roles_4 + calldata_Roles_32 + 4)
The code only checked if expression was in the condition, I added a check to see if the expression isn't prefixed with an underscore

Check if included expression is not prefixed by illegal character

---

mythril/analysis/modules/transaction_order_independence.py
tests/testdata/outputs_expected/calls.sol.o.json
tests/testdata/outputs_expected/calls.sol.o.markdown
tests/testdata/outputs_expected/calls.sol.o.text
tests/testdata/outputs_expected/weak_random.sol.o.json
tests/testdata/outputs_expected/weak_random.sol.o.markdown
tests/testdata/outputs_expected/weak_random.sol.o.text

This pr includes an analysis module that checks for the existence of TOD vulnerabilities. Fixes #122

Implement transaction order independence

---

mythril/analysis/modules/integer.py

There is a problem with taint checking which causes false negatives

Ignore added fp checks for now

---

mythril/ether/soliditycontract.py

change import statement

---

mythril/analysis/modules/integer.py
mythril/analysis/modules/transaction_order_independence.py
mythril/analysis/solver.py

Revert "Run overflow detection in a thread pool"

---

mythril/analysis/report.py

Only get filename if there is an issue

---

Dockerfile

Also pinning to bionic, to avoid surprises with versions bumps.

Slimmed down Dockerfile, with `myth` set as the entrypoint.

---

mythril/mythril.py

Update the signatures before creating the contract, as the contract uses the file not self.sigs
Fixes #208

Fix signature update

---

mythril/analysis/modules/multiple_sends.py

Add multiple send detection module

---

all_tests.sh

Just some small shell script changes to look and report on various test prerequisites.

Check and report status of various required packages

---

mythril/interfaces/cli.py
mythril/laser/ethereum/svm.py

Use bigger max depth in cli and increase depth on negative jumpi

---

mythril/analysis/modules/delegatecall.py
mythril/analysis/modules/transaction_order_independence.py

Bugfix regex

---

mythril/laser/ethereum/helper.py
mythril/laser/ethereum/natives.py
mythril/laser/ethereum/svm.py
tests/native_test.py
tests/native_tests.sol

gives native contract support for mythril.

add native contracts

---

mythril/laser/ethereum/svm.py

add type condition to jump

---

mythril/laser/ethereum/natives.py
mythril/laser/ethereum/svm.py

add typecheck for the contracts

---

mythril/analysis/modules/integer.py
tests/testdata/outputs_expected/ether_send.sol.json
tests/testdata/outputs_expected/ether_send.sol.o.json
tests/testdata/outputs_expected/ether_send.sol.o.markdown
tests/testdata/outputs_expected/ether_send.sol.o.text
tests/testdata/outputs_expected/metacoin.sol.o.json
tests/testdata/outputs_expected/metacoin.sol.o.markdown
tests/testdata/outputs_expected/metacoin.sol.o.text
tests/testdata/outputs_expected/overflow.sol.json
tests/testdata/outputs_expected/overflow.sol.markdown
tests/testdata/outputs_expected/overflow.sol.o.json
tests/testdata/outputs_expected/overflow.sol.o.markdown
tests/testdata/outputs_expected/overflow.sol.o.text
tests/testdata/outputs_expected/overflow.sol.text
tests/testdata/outputs_expected/underflow.sol.json
tests/testdata/outputs_expected/underflow.sol.markdown
tests/testdata/outputs_expected/underflow.sol.o.json
tests/testdata/outputs_expected/underflow.sol.o.markdown
tests/testdata/outputs_expected/underflow.sol.o.text
tests/testdata/outputs_expected/underflow.sol.text

Remove extra space mentioned in #295

Remove extra space in integer overflow output field

---

setup.py

Updates jinja dependency

---

mythril/disassembler/disassembly.py
mythril/laser/ethereum/svm.py

Use bytecode length as CODESIZE

---

mythril/laser/ethereum/svm.py
mythril/mythril.py

Get contract code from infura for EXTCODESIZE

---

mythril/laser/ethereum/strategy/basic.py
mythril/laser/ethereum/svm.py

Implements a search strategy based using dfs
fixes #289

Search strategy dfs

---

mythril/laser/ethereum/strategy/basic.py

Implement breadth first search

---

mythril/mythril.py

connect to infura only if needed

connect to infura with -l

---

mythril/laser/ethereum/instructions.py

Support 0x0 for extcodesize

---

mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py

This pr addresses the issues indicated in #288 
@norhh This is everything right?
Also fixes #321. this was caused by an assumption in svm.py to generate the cfg

wip: Worklist fixes

---

mythril/analysis/solver.py

Add timeout logging to solver

---

mythril/laser/ethereum/svm.py

Implement coverage measurement

---

mythril/ether/soliditycontract.py

Check for length bin runtime

---

mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state.py
mythril/laser/ethereum/svm.py
mythril/laser/ethereum/taint_analysis.py

Fixes #314 
This issue was actually an indication of a much bigger problem with the execution of calls, but that has been fixed now with this pr
edit: also fixes #346
edit2: also fixes #309

Bugfix 314

---

mythril/interfaces/cli.py
mythril/version.py
setup.py

Add -V and --version myth CLI option

---

mythril/support/truffle.py

Use solidity filename for truffle

---

mythril/ether/soliditycontract.py
mythril/support/truffle.py

Use bytes encoding to make the mapping

---

mythril/mythril.py
mythril/support/signatures.py

will correct the ambiguous in #369 and also some part of #377

Send a list for functions

---

mythril/analysis/modules/external_calls.py
mythril/analysis/modules/unchecked_retval.py
mythril/ether/evm.py
mythril/leveldb/client.py
mythril/leveldb/state.py
mythril/mythril.py
mythril/support/truffle.py

Fixes #364 . Mainly deleted camelCased local variables. If there's some other fixes to be done, I can change them in this PR or in another.

Remove capital letters from local variables

---

mythril/interfaces/cli.py

Remove reference to ipc

---

mythril/leveldb/client.py

Exclude invalid addresses from search results

---

mythril/analysis/symbolic.py
mythril/disassembler/disassembly.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state.py
mythril/laser/ethereum/svm.py
mythril/laser/ethereum/transaction.py
tests/laser/state/mstate_test.py
tests/laser/transaction/create.py

This pr implements a contract creation transaction in addition to the logic needed in laserEVM to start executing a contract with creation code.
closes #191

Contract creation transaction

---

mythril/support/signatures.py

fixes #409
Uses sys calls over file locking.

Add better lock support using sys calls

---

mythril/laser/ethereum/instructions.py

Move false case before the valid jumpdest check, as this can still succeed
fixes #427

Jumpi bugfix

---

mythril/laser/ethereum/svm.py

Implements code based coveraged and initial reporting

---

mythril/support/signatures.py

create signatures file if it doesn't exists.

Fix integration tests

---

mythril/laser/ethereum/call.py
mythril/laser/ethereum/state.py
tests/laser/state/mstate_test.py

Implements a dynamic pop for a machine state an applies it in call.py for some cleanups

Machine State dynamic pop implementation

---

mythril/laser/ethereum/taint_analysis.py

Filter on jumptype Transaction

---

.github/ISSUE_TEMPLATE/bug-report.md

Just trying to capture in the template what most people seem to be doing anyway.

Merge OS and OS-version fields

---

mythril/laser/ethereum/state.py
tests/laser/state/mstate_test.py

Implement memory write function

---

.circleci/config.yml

support sonar code coverage

---

mythril/laser/ethereum/taint_analysis.py

There were two important changes here:
1. Initially define the transaction_stack size to look for
We now had a bug where on ln 124 the runner could continue executing the next node, with a bigger transaction stack. That recursive call would thus have faulty assumptions.
2. Only look continue searching for direct children if the transaction_stack is bigger then then the size we're looking for. Otherwise the following might happen:
```
transactionA:
transactionB: <- we're analyzing this
transactionC:
transactionD: <- taint analysis assumed this was transaction B again
```
edit:
fixes #435

Use recursive transaction stack length passing

---

coverage_report.sh

Use xml coverage report

---

mythril/mythril.py

related to #506, change ganache's port to it's default.

Change ganache default to 8545

---

mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state.py
mythril/laser/ethereum/transaction/symbolic.py
tests/laser/evm_testsuite/evm_test.py
tests/laser/transaction/symbolic_test.py

This pr implements the suicide opcode

Suicide implementation

---

mythril/laser/ethereum/exceptions.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/svm.py
tests/laser/evm_testsuite/evm_test.py

Implements an invalid jumptype as an exception vs just returning []

InvalidJumpType modeling as a vm exception

---

README.md
mythril/laser/ethereum/evm_exceptions.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/svm.py

Implementation of the invalid opcode handler, this is now correctly modeled as a VmException

Invalid opcode exception

---

mythril/laser/ethereum/taint_analysis.py

check for existance of new records to work on

---

mythril/analysis/symbolic.py
mythril/analysis/traceexplore.py
mythril/ether/asm.py
mythril/ether/ethcontract.py
mythril/ether/evm.py
mythril/ether/util.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/util.py
mythril/leveldb/accountindexing.py
mythril/leveldb/client.py
mythril/leveldb/eth_db.py
mythril/leveldb/state.py
mythril/mythril.py
mythril/rpc/base_client.py
mythril/rpc/client.py
mythril/rpc/utils.py
mythril/support/loader.py
tests/native_test.py

This PR will
- add static methods where `self` is not needed
- remove redeclared variables that are not being used
- remove redundant brackets
- replace single-quoted with double-quoted ones (preparing for better docs in general)
- remove a trailing semicolon :scream:

Add static methods where needed and minor style fixes

---

mythril/ether/ethcontract.py

See https://github.com/ConsenSys/mythril/issues/69#issuecomment-428866633
Fix panic error for contract using library.

ethcontract: replace placeholder for library in creation_code

---

mythril/interfaces/cli.py
requirements.txt
setup.py

Added the `coloredlogs` dependency to get colored logging.

Added coloredlogs

---

mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/svm.py

Executes new transactions dynamically vs using the static number 2.
Right now it uses a limit of 3 transactions, this should be made configurable through the cli

Dynamic transaction execution

---

mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/svm.py
mythril/laser/ethereum/transaction/transaction_models.py

Implement revert opcode

---

mythril/analysis/symbolic.py
mythril/interfaces/cli.py
mythril/laser/ethereum/svm.py
mythril/mythril.py

Resolves #572
Signed-off-by: Stamatis Katsaounis <katsaouniss@gmail.com>

Add max-transaction-count cli parameter.

---

mythril/analysis/modules/multiple_sends.py

Fixes https://github.com/ConsenSys/mythril/issues/531

Grammar fix for "Multiple sends" warning text

---

README.md
mythril/disassembler/asm.py
mythril/disassembler/disassembly.py
tests/disassembler/asm.py

The module is moved to disassembler, it seems like this is a more logical place for it to be.
Additionally some refactoring and code simplification
Todo:

Refactor asm

---

mythril/analysis/modules/delegatecall.py
mythril/analysis/modules/dependence_on_predictable_vars.py
mythril/analysis/modules/deprecated_ops.py
mythril/analysis/modules/ether_send.py
mythril/analysis/modules/exceptions.py
mythril/analysis/modules/external_calls.py
mythril/analysis/modules/integer.py
mythril/analysis/modules/multiple_sends.py
mythril/analysis/modules/suicide.py
mythril/analysis/modules/transaction_order_dependence.py
mythril/analysis/modules/unchecked_retval.py
mythril/analysis/report.py
mythril/interfaces/cli.py
solidity_examples/rubixi.sol
tests/analysis/test_delegatecall.py

Coincidentally also includes some style changes (by black)

Add swc standard format output to mythril

---

mythril/analysis/modules/external_calls.py

Bugfix 633 State change after external call

---

mythril/analysis/modules/external_calls.py

Merges changes from #636 into new release branch

Hotfix ether send

---

mythril/analysis/modules/integer.py

Bugfix 634: Don't check for requires as this results in false negatives

---

mythril/analysis/solver.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/natives.py
mythril/laser/ethereum/state.py
mythril/laser/ethereum/transaction/transaction_models.py
tests/laser/state/calldata_test.py
tests/laser/transaction/symbolic_test.py

Includes:
Removing `ForAll` - Faster!
Minimizing `calldatasize` - No crazy long transactions.
Bugfixes

Related calldata and concretion improvements/fixes

---

mythril/analysis/modules/suicide.py
mythril/laser/ethereum/svm.py
mythril/support/truffle.py
tests/cmd_line_test.py
tests/native_test.py
tests/report_test.py
tests/svm_test.py

fixes #665 .
- Add mult transaction support to onchain analysis
- Take care of constraints for onchain analysis in suicide module

Add multiple transactions to onchain analysis and fix suicide module

---

mythril/analysis/analysis_utils.py
mythril/analysis/get_custom_constraints.py
mythril/analysis/modules/ether_send.py
mythril/analysis/modules/suicide.py
mythril/analysis/solver.py

fixes #676 
- support boolean constraints for solver
- support onchain analysis for ether_send module

Support Boolean constraints and support onchain analysis for ether_send

---

mythril/support/truffle.py

Quick fixes to truffle module.
fixes #597 , #607

Fix truffle source mappings and signatures

---

mythril/analysis/modules/external_calls.py
mythril/analysis/solver.py
mythril/ether/soliditycontract.py
mythril/interfaces/cli.py
mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/natives.py
mythril/laser/ethereum/svm.py
mythril/mythril.py
mythril/support/loader.py

`-v1` and `-v2` were inconsistent. Change debug levels so that `-v1` only outputs information related to progress and coverage.

Refactor logging and error messages (slightly)

---

mythril/mythril.py

Create empty signatures.json if file doesn't exist

Quick fix for #721

---

mythril/analysis/modules/integer.py

Add missing constraint to get_transaction_sequence args

---

mythril/ethereum/util.py
mythril/mythril.py
tests/cmd_line_test.py
tests/laser/transaction/create_transaction_test.py
tests/native_test.py
tests/solidity_contract_test.py
tests/svm_test.py

Quick fix for tests, uses `v0.4.24` at the moment

Quick fix for tests

---

mythril/interfaces/cli.py

When was the last time that you *didn't* add `-I`? 😉

Make infura-mainnet the default option in CLI

---

mythril/analysis/modules/integer.py
mythril/analysis/solver.py
mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/natives.py
mythril/laser/ethereum/state/calldata.py
mythril/laser/ethereum/state/environment.py
mythril/laser/ethereum/transaction/concolic.py
mythril/laser/ethereum/transaction/symbolic.py
mythril/laser/ethereum/transaction/transaction_models.py
tests/laser/state/calldata_test.py
tests/testdata/input_contracts/overflow.sol

Refactor of calldata

---

mythril/laser/ethereum/state/calldata.py

fixes #772 .
- have different variables for different calldatasizes
- calldata is 0 indexed, so considered that.

Calldata bugfixes

---

mythril/laser/ethereum/instructions.py

Related to the bug given by a contract in #661

simplify boolref in sstore_()

---

mythril/analysis/security.py
mythril/analysis/symbolic.py
mythril/mythril.py

closes #776. Only executes modules passed in with `-m/--module`.

Only execute callback modules when needed

---

mythril/analysis/modules/external_calls.py

Convert 1 arg to BitVecVal

---

requirements.txt
setup.py

Fix py_ecc version

---

mythril/analysis/solver.py

fixes #801 .
it seems minimizing transaction count isn't that trivial(and i did something terrible there), so reverting it at the moment.

Reverts minimizing transaction count

---

mythril/laser/ethereum/state/global_state.py
mythril/laser/ethereum/state/world_state.py

queryable annotations

---

mythril/analysis/modules/delegatecall.py

fixes #789,
Also fixes the calldata regex for delegatecall issue. previously it searched for calldata.*_0, now it's searching for `calldata.*[0` kind of elements.

Callback refactor for delegatecall module

---

mythril/analysis/solver.py

use z3 simplify on variables extracted from z3.Model

---

mythril/analysis/modules/delegatecall.py
mythril/laser/ethereum/instructions.py
mythril/laser/smt/__init__.py
mythril/version.py

- Checks whether call object is None or not in delegatecall module
- Converts python bool to z3 bool to support `Or()` in sstore.

Some minor fixes

---

mythril/analysis/modules/multiple_sends.py

Refactor multiple_sends.py

---

mythril/laser/ethereum/state/account.py

Put BitVecVals into the storage

---

mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state/account.py
mythril/laser/ethereum/state/memory.py

Put BitVecVals in stack

---

mythril/laser/ethereum/cfg.py
mythril/laser/ethereum/transaction/concolic.py
mythril/laser/ethereum/transaction/symbolic.py

Add function name to node initialization

---

mythril/alarm.py
mythril/exceptions.py
mythril/laser/ethereum/svm.py

Closes #673
Tell Windows I'm sorry.

Implement sigalrm timeout

---

mythril/laser/ethereum/call.py

Implement special case for the delegatecall proxy pattern

---

mythril/laser/ethereum/svm.py

hopefully fixes #877 . @nbanmp can you test whether it actually fixes?

Add the return constraints to global state

---

Dockerfile
MANIFEST.in
mythril/mythril.py
setup.py

signatures file in . directory isn't taken by docker.So docker-dev isn't working, is moving it to mythril.support

Move the signatures file to support

---

mythril/laser/ethereum/instructions.py

Eliminate 0x in the bytecode while searching for offset

---

mythril/analysis/solver.py
mythril/laser/ethereum/plugins/mutation_pruner.py
mythril/laser/ethereum/svm.py
mythril/laser/ethereum/time_handler.py
mythril/laser/smt/bool.py
mythril/laser/smt/solver.py
mythril/support/support_utils.py
requirements.txt
setup.py
tests/laser/transaction/create_transaction_test.py

Also fixes #899 , was required to fix to test for various other contracts.

Change solver's timeout based on execution-timeout

---

mythril/laser/ethereum/state/constraints.py

Running on Bectoken results in an error.
```
File "/home/nikhil/MYTHRIL/rbval/mythril/mythril/mythril.py", line 586, in fire_lasers
enable_iprof=enable_iprof,
File "/home/nikhil/MYTHRIL/rbval/mythril/mythril/analysis/symbolic.py", line 102, in __init__
creation_code=contract.creation_code, contract_name=contract.name
File "/home/nikhil/MYTHRIL/rbval/mythril/mythril/laser/ethereum/svm.py", line 146, in sym_exec
self._execute_transactions(created_account.address)
File "/home/nikhil/MYTHRIL/rbval/mythril/mythril/laser/ethereum/svm.py", line 182, in _execute_transactions
execute_message_call(self, address)
File "/home/nikhil/MYTHRIL/rbval/mythril/mythril/laser/ethereum/transaction/symbolic.py", line 58, in execute_message_call
laser_evm.exec()
File …
```

Use only Bool in constraints

---

tests/__init__.py

Create test output folders if they don't exist

---

mythril/laser/smt/solver.py

Redirect stdout to null when executing self.raw.check()

---

mythril/analysis/modules/integer.py
tests/report_test.py
tests/testdata/outputs_expected/calls.sol.o.json
tests/testdata/outputs_expected/ether_send.sol.o.json
tests/testdata/outputs_expected/exceptions.sol.o.json
tests/testdata/outputs_expected/kinds_of_calls.sol.o.json
tests/testdata/outputs_expected/metacoin.sol.o.json
tests/testdata/outputs_expected/multi_contracts.sol.o.json
tests/testdata/outputs_expected/nonascii.sol.o.json
tests/testdata/outputs_expected/origin.sol.o.json
tests/testdata/outputs_expected/overflow.sol.o.json
tests/testdata/outputs_expected/overflow.sol.o.markdown
tests/testdata/outputs_expected/overflow.sol.o.text
tests/testdata/outputs_expected/returnvalue.sol.o.json
tests/testdata/outputs_expected/suicide.sol.o.json
tests/testdata/outputs_expected/underflow.sol.o.json
tests/testdata/outputs_expected/underflow.sol.o.markdown
tests/testdata/outputs_expected/underflow.sol.o.text

This pr will add a bit of false positive filtering to the integer over&underflow module.
It will only report a vulnerability if:
- there is an overflow somewhere
- used by an sstore or STOP
- for which there is a trace that succesfully finishes
fixes #782

Effect check

---

mythril/interfaces/cli.py

increase max depth to 50 and move to bfs

---

mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state/world_state.py

Fix address length and mstore8_ opcode

---

mythril/analysis/modules/integer.py

will fix a part of the bug in #935 .

handle return for integer module

---

mythril/analysis/report.py
mythril/interfaces/cli.py
mythril/mythril.py

Support error logs for swc json format

---

solidity_examples/WalletLibrary.sol
solidity_examples/rubixi.sol

The opposite condition was put in those examples compared to the actual ones.
I think it might be good to revert these examples to older versions as that version caused the actual bug

Fix rubixi.sol and walletlibrary.sol

---

mythril/analysis/report.py
tests/report_test.py
tests/testdata/outputs_expected/calls.sol.o.jsonv2
tests/testdata/outputs_expected/ether_send.sol.o.jsonv2
tests/testdata/outputs_expected/exceptions.sol.o.jsonv2
tests/testdata/outputs_expected/kinds_of_calls.sol.o.jsonv2
tests/testdata/outputs_expected/metacoin.sol.o.jsonv2
tests/testdata/outputs_expected/multi_contracts.sol.o.jsonv2
tests/testdata/outputs_expected/nonascii.sol.o.jsonv2
tests/testdata/outputs_expected/origin.sol.o.jsonv2
tests/testdata/outputs_expected/overflow.sol.o.jsonv2
tests/testdata/outputs_expected/returnvalue.sol.o.jsonv2
tests/testdata/outputs_expected/suicide.sol.o.jsonv2
tests/testdata/outputs_expected/underflow.sol.o.jsonv2

Display the discoveryTime

---

mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/support/loader.py

Remove unnecessary variable from dynamic loading function

---

mythril/analysis/symbolic.py
mythril/laser/ethereum/plugins/plugin_factory.py
mythril/laser/ethereum/plugins/plugin_loader.py
requirements.txt
setup.py

Use plugin loader and factory

---

mythril/analysis/symbolic.py
mythril/laser/ethereum/plugins/implementations/benchmark.py
mythril/laser/ethereum/plugins/implementations/coverage.py
mythril/laser/ethereum/svm.py

Removes coverage related logic from core svm
Extends the instruction coverage plugin with functionality to report coverage increase between transactions
closes #978

Use instruction coverage plugin

---

mythril/support/source_support.py

Add creation hash to the code

---

mythril/analysis/report.py
mythril/interfaces/cli.py

Fixes #999.
Note: #1000 Yay! :tada:

Fix jsonv2 log format

---

CONTRIBUTING.md
mythril/interfaces/cli.py
mythril/laser/ethereum/svm.py

Fix some small typos in comments, documentation, and variable names.

Fix some minor typos

---

docs/source/module-list.rst

update detection capabilities

---

README.md
mythril/analysis/modules/dos.py

This module returns a low severity warning when a state change or call is executed in a loop. It correctly detects the following SWC test cases:
https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-128#dos-addresssol
https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-128#dos-numbersol
https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-128#dos-simplesol

Add DOS detection module

---

mythril/analysis/modules/base.py
mythril/analysis/modules/delegatecall.py
mythril/analysis/modules/dependence_on_predictable_vars.py
mythril/analysis/modules/deprecated_ops.py
mythril/analysis/modules/dos.py
mythril/analysis/modules/ether_thief.py
mythril/analysis/modules/exceptions.py
mythril/analysis/modules/external_calls.py
mythril/analysis/modules/integer.py
mythril/analysis/modules/multiple_sends.py
mythril/analysis/modules/state_change_external_calls.py
mythril/analysis/modules/suicide.py
mythril/analysis/modules/unchecked_retval.py
mythril/analysis/security.py
mythril/interfaces/cli.py

- Pass on loglevel to modules on import
- [Consistency] Move module enter/exit log messages to base module
- [Consistency] Remove return statements from some execute methods
Fixes #1035

Refactor modules / logging and consistency

---

mythril/analysis/modules/ether_thief.py

Add constraints on sender and receiver

---

mythril/version.py

This PR adds fixes false positives on several SWC-105 samples.

Fix for Ether Thief false positives

---

mythril/analysis/symbolic.py
mythril/mythril/mythril_analyzer.py

Add a check for analysis modules run

---

mythril/analysis/modules/suicide.py

Fix suicide module by constraining to attacker

---

docs/source/installation.rst
docs/source/security-analysis.rst

Update docs after cli refactor

---

mythril/laser/ethereum/strategy/extensions/bounded_loops.py

Simplify bounded loops extension

---

mythril/analysis/modules/dependence_on_predictable_vars.py

Check for None as constraints

---

mythril/laser/ethereum/state/account.py
mythril/laser/smt/bitvec.py
mythril/laser/smt/bitvecfunc.py

Handle BitVecFunc inputs

---

mythril/analysis/modules/integer.py
mythril/analysis/symbolic.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state/machine_state.py
mythril/laser/ethereum/state/memory.py
mythril/laser/smt/bitvec.py
mythril/laser/smt/bitvecfunc.py

Fixes memory

---

mythril/analysis/modules/dos.py

Avoid symbolic targets

---

mythril/analysis/solver.py

That was an embarrassing bug :man_facepalming:.

Fix the json v2 accounts field

---

mythril/laser/smt/__init__.py
mythril/laser/smt/bitvec.py

fixes #1152 , but not that major bug.
Also fixes typehints for new version of mypy.

Fix the padding while comparing

---

mythril/analysis/symbolic.py
mythril/interfaces/cli.py
mythril/laser/ethereum/svm.py
mythril/mythril/mythril_analyzer.py

Enable coverage based search strategy through CLI with "--enable-code-coverage".

Enable coverage based search strategy through CLI

---

mythril/analysis/modules/ether_thief.py
mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state/account.py
mythril/laser/ethereum/svm.py

That I encountered when reading the code.
- comments
- good practices to increase readability
- unused variables
- TODOs (not fixing them, because I'm not sure how to yet, and I want to keep this PR purely minor fixes)

Various small fixes.

---

requirements.txt
setup.py

Fix dependency conflict for issue

---

.circleci/config.yml
mythril/analysis/security.py
mythril/analysis/symbolic.py
mythril/interfaces/cli.py
mythril/mythril/mythril_analyzer.py

Allows the running of custom modules in addition to built-in modules by way of specifying the custom modules directory with the --custom-modules-directory option.

Refactored interfaces to allow custom modules

---

mythril/analysis/report.py
mythril/interfaces/cli.py
mythril/interfaces/old_cli.py

Fixing some processing errors.

"true" to True

---

mythril/analysis/solver.py
mythril/laser/ethereum/call.py
mythril/laser/ethereum/state/account.py

Also fix another serialization bug that appears now that the printable
storage is not empty.

Fix a bug: correctly copy printable storage over

---

mythril/analysis/modules/ether_thief.py
mythril/analysis/solver.py

Fix Regression problem with one contract + add minimise

Fix some ether problems and fix minimise

---

mythril/laser/ethereum/call.py

This is the core fix for issue #674
Note that another PR is still needed to propagate annotations for that bug to be fully fixed.

Fix support for calls forwarding the entire calldata.

---

mythril/interfaces/cli.py

Some cleanup in cli and adds some help. fixes #1009

Refactor the cli and add help for the contract selection

---

mythril/laser/ethereum/plugins/implementations/dependency_pruner.py
mythril/laser/ethereum/plugins/implementations/mutation_pruner.py
mythril/laser/ethereum/plugins/implementations/plugin_annotations.py
mythril/laser/ethereum/state/global_state.py
mythril/laser/ethereum/svm.py

Fixes A20-200
- Only propogates Mutation annotations when in delegatecall or codecall
- some reorder of classes due to circular imports

Only propagate code based call annotations

---

mythril/analysis/modules/delegatecall.py

Check delegatecall after transaction execution finishes

---

mythril/analysis/modules/delegatecall.py

added the return value check constraint for delegatecall

Add the return condition

---

mythril/laser/ethereum/state/global_state.py

Just a small thing that bothered me while I was going over the recent changes 😅

Immediately return value

---

mythril/ethereum/util.py

I wanted to add this for months...

Enable optimizer when compiling Soldity files

---

mythril/laser/smt/bitvecfunc.py

Use padded operation over operation

---

mythril/analysis/modules/external_calls.py
mythril/analysis/modules/state_change_external_calls.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/natives.py

Also balance_() opcode uses wrong address.

Refactor code by removing usused and repeated code

---

mythril/analysis/modules/integer.py
mythril/ethereum/interface/leveldb/client.py
mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state/global_state.py
mythril/laser/ethereum/svm.py

Apparently constraints from constructor aren't being moves previously.
Also fixes new black formatting problems due to new version

Fixes regression

---

mythril/laser/ethereum/instructions.py

Fix a codecopy bug

---

tests/solidity_contract_test.py
tests/testdata/input_contracts/calls.sol
tests/testdata/input_contracts/constructor_assert.sol
tests/testdata/input_contracts/environments.sol
tests/testdata/input_contracts/ether_send.sol
tests/testdata/input_contracts/exceptions.sol
tests/testdata/input_contracts/kinds_of_calls.sol
tests/testdata/input_contracts/metacoin.sol
tests/testdata/input_contracts/multi_contracts.sol
tests/testdata/input_contracts/nonascii.sol
tests/testdata/input_contracts/origin.sol
tests/testdata/input_contracts/overflow.sol
tests/testdata/input_contracts/returnvalue.sol
tests/testdata/input_contracts/rubixi.sol
tests/testdata/input_contracts/suicide.sol
tests/testdata/input_contracts/underflow.sol
tests/testdata/input_contracts/weak_random.sol

For supporting newer solc versions

Prefix versions

---

mythril/laser/ethereum/state/account.py

fixes #1270, probably. I don't have any specific proof of concept contracts to test against.
My theory is that the issues are reported in contracts that the contract we are analyzing called, and the addresses of those contracts are not reported.

Fix contract names of deployed contracts

---

mythril/laser/ethereum/call.py
tests/native_test.py

Add a retval before returning in native calls

---

mythril/analysis/modules/integer.py

Handle the case for bool

---

mythril/laser/ethereum/strategy/extensions/bounded_loops.py

Loop bound only JUMPIs

---

.pre-commit-config.yaml
requirements.txt

I've gone ahead and added pre-commit configuration to mythril.
After you've executed `pre-commit install` you'll always have a very nice pre-commit hook that fixes up black and everything. ⚫️  🎉 
I'll let @norhh approve these change's before actually applying it, because some of the hooks edit a ton of files.

Add pre commit to repo

---

mythril/ethereum/interface/rpc/client.py

The latest infura doesn't need a port.

Quick fix for localhost rpc

---

mythril/interfaces/cli.py
mythril/laser/ethereum/state/account.py
mythril/mythril/mythril_analyzer.py
mythril/support/support_args.py

fixes #1362 .
Also, this will have unconstrained storage while executing delegatecall

Unconstrained storage

---

mythril/interfaces/cli.py
mythril/laser/ethereum/call.py
tests/instructions/create2_test.py
tests/instructions/create_test.py

Fixes a case where 3rd nested call reverts due to incorrect calldata.

Fix a multicontract bug

---

mythril/analysis/symbolic.py

Plugins would not run without instrumenting.

Instrument laser with plugins

---

mythril/analysis/module/modules/unchecked_retval.py

Fix unchecked retval

---

mythril/laser/ethereum/instructions.py
requirements.txt

This pullrequest adds more accurate handling of the signextend instruction modelling.
In particular, it accepts situations where the sign bit is symbolic.

Fix edge case where sign_bit_set is symbolic

---

mythril/interfaces/cli.py
mythril/laser/plugin/plugins/call_depth_limiter.py

Fixes crash when call_depth_limiter is triggered, example
```
./myth -v4 a -c 608060405234801561001057600080fd5b50730901d12ebe1b195e5aa8748e62bd7734ae19b51f600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555073384f682f4a5abefc8795cc38a340de9446dfae7a6000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061044a806100c96000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806329e99f0714610030575b600080fd5b61004a6004803603810190610045919061025c565b610060565b60405161005791906102c5565b60405180910390f35b6000808260008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16639c8834 …
```

Fix a small issue with call limiter

---

mythril/analysis/report.py
mythril/solidity/soliditycontract.py

Handle file mapping to yul files

---

mythril/ethereum/util.py
tests/solidity_contract_test.py

Fix issues with optimizer

---

mythril/ethereum/util.py
tests/integration_tests/analysis_tests.py
tests/integration_tests/test_solc_settings.py
tests/testdata/json_test_dir/PRC20.sol
tests/testdata/json_test_dir/dir_a/input_file.sol
tests/testdata/json_test_dir/test_file.json

Fix json issue

---

mythril/mythril/mythril_disassembler.py

Fix error message

---

mythril/ethereum/interface/leveldb/eth_db.py

closes #1509 
This PR circumvents the usage of plyvel when it's not needed.

Ignore plyvel

---

mythril/laser/ethereum/svm.py

Remove additional eth transfer

---

mythril/laser/ethereum/state/global_state.py
mythril/laser/plugin/plugins/coverage/coverage_plugin.py

Fix issues with out of index code

---

mythril/ethereum/util.py
mythril/laser/ethereum/function_managers/keccak_function_manager.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/state/constraints.py
mythril/laser/ethereum/svm.py
mythril/support/model.py
tests/integration_tests/test_safe_functions.py
tests/laser/keccak_tests.py
tests/solidity_contract_test.py

Currently, concrete values from the future are not considered. This PR fixes this.

Fixes issues by considering future concrete hashes

---

mythril/laser/ethereum/state/account.py

Fix onchain storage access

---

mythril/laser/ethereum/state/world_state.py
mythril/support/loader.py

Fix case where loader is not present

---

mythril/laser/ethereum/state/world_state.py

Fixes issues with calls to addresses without code

Use empty code to denote address

---

mythril/laser/ethereum/state/world_state.py

Use concrete storage

---

mythril/analysis/module/modules/integer.py
requirements.txt

Fixes issues with NoneType and restricts rlp version

---

mythril/analysis/report.py
mythril/disassembler/disassembly.py

Support multiple function names

---

myth
mythril/ethereum/util.py
mythril/laser/plugin/plugins/coverage/coverage_plugin.py

Handle cases with symbolic bytecode

---

mythril/mythril/mythril_disassembler.py

Will download itself if missing.
myth analyze simple.sol --solv v0.5.16
The analysis was completed successfully. No issues were detected.

Allow missing solc

---

mythril/ethereum/util.py
mythril/mythril/mythril_disassembler.py
requirements.txt
tests/util_tests.py

Support Pragmas

---

mythril/analysis/module/base.py
mythril/analysis/module/modules/arbitrary_jump.py
mythril/analysis/module/modules/arbitrary_write.py
mythril/analysis/module/modules/delegatecall.py
mythril/analysis/module/modules/dependence_on_origin.py
mythril/analysis/module/modules/dependence_on_predictable_vars.py
mythril/analysis/module/modules/ether_thief.py
mythril/analysis/module/modules/exceptions.py
mythril/analysis/module/modules/external_calls.py
mythril/analysis/module/modules/integer.py
mythril/analysis/module/modules/multiple_sends.py
mythril/analysis/module/modules/state_change_external_calls.py
mythril/analysis/module/modules/suicide.py
mythril/analysis/module/modules/unchecked_retval.py
mythril/analysis/module/modules/user_assertions.py
mythril/analysis/potential_issues.py
mythril/support/support_utils.py

Better caching -> 20-30% speedup 🚀

Fix caching of issues across modules

---

mythril/laser/ethereum/cfg.py

Use int argument

---

mythril/analysis/module/base.py
mythril/analysis/module/modules/exceptions.py
tests/integration_tests/test_safe_functions.py

Sometimes different asserts use the same lines of code, which messes up with source mapping.

Fix caching for exceptions module

---

mythril/laser/ethereum/instructions.py

Fix Bitvec issue

---

mythril/interfaces/cli.py
tests/cmd_line_test.py
tests/integration_tests/analysis_tests.py
tests/integration_tests/test_safe_functions.py
tests/integration_tests/test_src_mapping.py
tests/integration_tests/utils.py
tests/integration_tests/version_test.py

Add exit code

---

mythril/analysis/module/modules/exceptions.py

"filename": "mythril/analysis/module/modules/exceptions.py"
"warning_type": "Incompatible variable type [9]"
"warning_message": " last_jump is declared to have type `int` but is used as type `None`."
"warning_line": 28
"fix": None to 0

last_jump has type `int` but is used as type `None`.

---

mythril/analysis/module/modules/unchecked_retval.py
mythril/laser/ethereum/call.py
mythril/laser/ethereum/instructions.py
mythril/laser/ethereum/svm.py

Handle OOG during CALL
