ConsenSys/mythril

- myth
Based on [PR #12 ](https://github.com/b-mueller/mythril/pull/12)
**2 main supports added**
1. Simpler/shorter command when using Infura Node service:
Support more user-friendly rpchost, rpctls setting by specifying `--infura-mainnet="True"` which is equivalently to setting the following three options one by one 
`--rpchost "mainnet.infura.io/{INFURA_KEY}" --rpcport "443" --rpctls="True"`
Namely, now to get opcode, use:
```shell
./myth --infura-mainnet="True" -d -a "0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208"
```
2. Add testnet supports (rinkeby, kovan and ropsten)
For most projects, deployment and bug bounty program are on testnet. Therefore, I think adding testnet support is useful for code audit team. 
Also using infura node on testnet. An example to produce CFG of [this contract on …
> add support for testnet & friendly shorter option using infura

- mythril/ether/contractstorage.py
This corrects the bug where mythril skips all contracts if the `--sync-all` flag is used.
> corrected sync-all flag logic

- mythril/analysis/modules/weak_random.py
- solidity_examples/weak_random.sol
Currently the module looks for common predictable state variables in ether transfer constraints
Sample output:
==== Weak random ====
Type: Warning
Contract: WeakRandom
Function name: _function_0xe9874106
PC address: 1285
In the function '_function_0xe9874106' the following predictable state
variables are used to determine Ether recipient:
- block.coinbase
TODO:
- block.blockhash(block.number-1)
- block.blockhash(some_block_past_256_blocks_from_now)==0
- external source of random numbers (e.g. Oraclize)
> add basic detection of faulty PRNGs

- security_checks.md
Thought perhaps you might find an update to the security readme useful.
* Weak Randoms module link moved to the correct column
* Additional direct links to Consensys security issues
* Denote that the "Call Depth Attack" has been deprecated with the EIP150 Hard Fork
Love this project, btw!
> update security readme

- myth
- mythril/support/truffle.py
Now you can do stuff like `myth -to json` (it will output a json object per contract).
> Allow for different output formats in truffle projects

- README.md
An issue with the recent tickets I've submitted (#75, #76) comes from not having the latest version. Since this project actively being developed, it may be useful to have the current pypi version programmatically displayed on the README. This uses 
https://badge.fury.io/
to render the badge, with the version taken from pypi itself. It should render like this:
[![PyPI](https://badge.fury.io/py/mythril.svg)](https://pypi.python.org/pypi/mythril)
> Add badge to README to indicate latest pypi version

- mythril/ether/__init__.py
- mythril/ether/contractstorage.py
- mythril/ipc/client.py
I see in this issue: <https://github.com/ConsenSys/mythril/issues/90>, current myth is quite slow to read data from ipc socket after removing web.py.
Current implementation of reading data from socket, has 2 issues with performance I think:
1. it connects the ipc socket every time, and the operation is expensive
2. it doesn't know if the response is complete, so it will still call `socket.recv` until the time is out, and the timeout is at least 0.2 second
The implementation is inspired from web3.py.
When I run the code (by command `myth --init-db`), it show me about 1 second for each IPC call, which is too slow (if you add `print(blockNumber)` in `contractstorage.py#initialize`)
In this PR, I tried 2 improvements:
1. reuse the socket all the time, across ipc calls, to reduce the …
> fix #90: try speeding up ipc reading

- mythril/analysis/modules/integer.py
Adds a type check for op0 or op1, to ensure it doesn't get passed to z3
> Add type check

- requirements.txt
fixes #144 
eth-tester depends on a lower version of rlp than was implicitly pulled in.
> explicitly satisfy rlp dependency

- mythril/analysis/modules/integer.py
@maurelian found that while analyzing https://github.com/aragon/aragon-apps/blob/master/apps/voting/contracts/Voting.sol. Mythril would fail:
This happened because ULT(a, b) fails if both a and b are an int. The contract contains a situation where both op0 and op1 are ints, so expr is also an int (which triggered the problem).
This pr fixes the problem by putting op0 and op1 in bitvecs if they are ints
> Change ints to bitvec

- Pipfile
- setup.py
It seems that the pip package does not include a version requirement for rlp, this causes fresh installs to be invalid. This pr adds a version definition for the rlp package
> Define version for rlp

- .circleci/config.yml
- mythril/analysis/modules/integer.py
I added two things to limit false positives.
_check_requires(state, node, statespace, constraint) is now used to check if a potentially interesting jumpi statement isn't part of a requires statement by checking if one of its children has a revert/assert_fail instruction.
The second part was the addition of constraint checking while searching children for usage of a tainted variable. Only reachable children with the exploitation constraint will be checked
Fixes #159
> [wip] Integer false positive detection

- mythril/analysis/modules/integer.py
When checking if we can influence a value we should not consider the overflow constraint as this will lead to false positives with ++ operations. Fixes #176
> Bugfix _verify_integer_overflow

- mythril/analysis/modules/integer.py
If one of the operands can be zero, then the module mistakenly assumed an overflow. This is now fixed.
Additionally, I cleaned up the _verify_integer_overflow method.
Fixes #190
> Bugfix integeroverflow

- mythril/mythril.py
Issues for non SolidityContracts were ignored in the new cli module due to an indentation error. Fixes #193
> Bugfix reporting non solidity projects

- setup.py
Templates were not being included in the setuptools-bundled version of mythril. This should resolve the problem.
> Fixes setup.py to include templates

- requirements.txt
- setup.py
ethereum 2.3.2 needs rlp 1.0.1. Just as a temporary fix until we shift to rlp 1.0.1
> fix ethereum to 2.3.1

- mythril/disassembler/disassembly.py
- mythril/mythril.py
- mythril/support/signatures.py
Attempts to refactor the support/signatures modules to provide a `Signatures()` class which loads signatures from a specified path or from the default location. Optionally queries an online database to resolve function signatures.
The online database is https://4byte.directory (>65k sigs). I maintain a project at [smart-contract-sanctuary](https://github.com/tintinweb/smart-contract-sanctuary) that dumps contracts from etherscan.io and submits them to https://4byte.directory - this should even increase the coverage in the future.
As noted as a todo in `signatures.py` once this PR has been merged I'll submit another that moves the signature utility functionality to this class in order to have one interface to signatures.
**Dependencies:**
https://github.com/tintinweb/ethereum-input-decoder …
> Feature: online signature hash lookup and signatures refactor

- mythril/laser/ethereum/instructions.py
Simplify can only be used for z3 expr and op0 may or may not be a z3 expr.
> check for z3 before simplify

- mythril/interfaces/cli.py
- mythril/leveldb/client.py
- mythril/mythril.py
- setup.py
There is no more reason to restrict search to >0 balance contracts (this was originally done to keep the contract database small).
This PR removes the feature. We can re-introduce a "min_balance" search condition later if needed.
Also: 
- Output a progress message every 1,000 contracts (with -v1)
- Remove calculation of MD5 hash for every contract (was an artifact from before)
> Refactor search

- mythril/laser/ethereum/instructions.py
Missing _ will not find the appropriate function when handling the codecopy instruction
> Addin _ to codecopy function

- mythril/laser/ethereum/instructions.py
- mythril/leveldb/client.py
Interestingly codecopy seems to fail for some contracts like [0x88c1f00DF493673f72aa0481187A0Ff8c5ad0E14](https://etherscan.io/address/0x88c1f00DF493673f72aa0481187A0Ff8c5ad0E14#code) due to the fact that IndexError won't be thrown for slices which I realized recently(now). We may need to change in some other places too for this reason.
Also some leveldb cleanup
> Fix codecopy for edge cases

- README.md
- setup.py
Hi,
quickly talked about this with @b-mueller.
finally found a way to directly push markdown to pypi instead of having to convert it to RST first. Changed `setup.py` to make use of this feature. This will push the `sdist` and `bdist_wheel` (python preferred) to pypi.
* somewhat up2date versions of pip, wheel, setuptools and twine `pip install --upgrade pip wheel setuptools twine`
1. `#> python setup.py sdist bdist_wheel`
2. `#> twine upload <build_location>` usually `#> twine upload dist/*` (or specific build from ./dist)
2.1 optional parameters: `--repository <named_repo_from_pypirc>` or `--repository-url <url: testpypi, pypi>`
Note: this PR removes the hardcoded `long_description` from `setup.py` and reads `Readme.md` when publishing to pypi.
https://test.pypi.org/project/mythrilxx/
> setup.py - publish Readme.md as markdown to pypi.python.org removing hardcoded long_description (and build wheel)

- mythril/laser/ethereum/taint_analysis.py
The previous method did not account for delegate calls and codecalls
> Perform check based on transaction_stack

- mythril/laser/ethereum/state.py
- mythril/laser/ethereum/svm.py
- mythril/laser/ethereum/transaction.py
By default mythril will assume contract storage is still "symbolic". This means that if you SLOAD an unset storage slot it will assume its a symbol. This pr adds support for the concrete assumption (which is the case for multi-transactional analysis) in which case it will return 0 if an unset storage slot is queried.
Fixes #423
> Implements concretized storage

- mythril/laser/ethereum/svm.py
Executes 2 transactions by default, in the future we might want to do this based on coverage
Additionally adds hinting if no contract was created during the contract creation transaction execution
> Do multiple transactions

- mythril/interfaces/cli.py
Many shells have a limit on the length of command-line arguments, so including the full bytecode of a large contract to be analysed on the command line may be impossible. Hence, I have added an option for loading the bytecode directly from a file.
> Add support for loading bytecode from file

- mythril/analysis/symbolic.py
- mythril/laser/ethereum/svm.py
- mythril/laser/ethereum/transaction/symbolic.py
During contract creation the account name of the created account was not set, with this pr it will be set to the name of the original contract in symbolic.py
closes #458
> Initialize account with contract name

- mythril/laser/ethereum/transaction/symbolic.py
The constraints of the previous transaction where ignored. Which means that if we're examining a situation in transaction 2, then its assumed that the input for transaction 1 is unconstrained.
Which is of course not correct, this pr fixes that
Note for the future. Atm we have 2 locations where constraints are stored, make this unified
> Carry constraints with new transaction

- mythril/analysis/templates/callgraph.html
The problem here is that the added `<!DOCTYPE html>` makes the browser switch from [quirks mode](https://en.wikipedia.org/wiki/Quirks_mode) to standards mode. While that's what you usually want when declaring a doctype, it can break some layout logic.
In standards mode, elements like `html` and `body` don't occupy the whole page anymore but instead wrap around the smallest element. As only the network canvas had an explicit height defined (but it was calculated and fairly small), the body wrapped around the tiny canvas and all other relative heights took that as a reference point - making the whole layout small.
The solution is to explicitly assign a relative height to `html` and `body` tags and then scale up the UI elements relative to them. Also removed a redundant p-tag around the …
> Fix issue 488: Broken CFG HTML output

- Dockerfile
- mythril/interfaces/cli.py
- requirements.txt
Fixes #479 
The report-generated output from the text and markdown functions returned text in UTF-8 encoding. The `print` function has an implicit encoding in ASCII. It tried to decode the bytes passed to it and crashed. The solution was to explicitly encode the input as UTF-8. This should also work when Mythril is run locally.
To make extra sure, I have set `PYTHONIOENCODING=UTF-8` in the Docker container's environment, which overrides the implicit print behaviour and encodes to UTF-8 by default.
> Fix Docker container crash with UnicodeEncodeError

- mythril/analysis/modules/multiple_sends.py
This pr makes the analysis module stop at the boundary of a new transaction, which is of course a requirement for this vulnerability
fixes #510
> Bugfix Multiple send

- mythril/analysis/modules/multiple_sends.py
Looks like "Informational" rather than "Information" seems to be what's used most often. Fixes #529 .
> Severity type "Information" -> "Informational" to match the others

- mythril/support/signatures.py
Hi,
mythril signature db does not check if the folder structure is set up (e.g.`~/.mythril/`) before calling `signaturedb.write()`. This PR checks if the folder exists and if not mkdirs it. Autocreating the folder is expected behavior as one can explicitly call `signature.write()` even if the signaturedb file does not yet exist.
only happens when using mythril as a library. otherwise mythril would initially setup the folder.
this was reported in https://github.com/tintinweb/ethereum-dasm/issues/10 
cheers,
tin
> fix mythril signature db throwing FileNotFoundError when using mythril as a library

- mythril/analysis/modules/external_calls.py
- mythril/analysis/modules/integer.py
- mythril/ether/asm.py
- mythril/laser/ethereum/state.py
- mythril/laser/ethereum/taint_analysis.py
- mythril/mythril.py
This fixes a common Python gotcha. Default arguments are evaluated only once when the function is *defined*. Mutable default arguments thus are declared once in memory and referenced over and over again when used. A simple example:
```python
In [9]: def append_to_list(value, l=[]):
...:     l.append(value)
...:     return l
...: 
In [10]: append_to_list(42)
Out[10]: [42]
In [11]: append_to_list(1337)
Out[11]: [42, 1337]
```
On the second function call you might have expected `[1337]` to return, however what you get is the mutable default type's appended version. This might introduce some subtle bugs where e.g. more states are in a list (and evaluated) than there actually are. The solution is to simply define a new list at runtime if no argument is given.
> Fix mutable args

- mythril/ether/util.py
- mythril/mythril.py
- mythril/support/signatures.py
Now your can run it against a truffle project with the appropriate options.
To test it, create a new truffle project with some dependencies to openzeppelin and run:
```
$ myth --solc-args "openzeppelin-solidity=/Users/max/work/ponycontract/node_modules/openzeppelin-solidity --allow-paths /Users/max/work/ponycontract/node_modules/openzeppelin-solidity" \
-x contracts/ponycontract.sol
```
Previously it was failing due to the `import_from_solidity_source` method that was ignoring the `solc-args` and then it was failing due to multiple `--allow-paths` args provided to `solc`.
Note: I'm not proud of the argument cleanup function, I tried to find some utilities in the python library but didn't find any.
> Fix a couple of issues with the solc-args option

- mythril/support/truffle.py
This prevents passing custom `solc` arguments which is important in some
cases (for example, `--allow-paths` is a very useful option)
Solution: pass solc_args through
> Problem: truffle project analysis ignores --solc-args

- Dockerfile
Currenlty, every time a docker container is rebuilt for updated source
code of the package, it'll start from scratch. This means it will not
reuse layers with existing Python, solc, etc. installation.
Solution: install Python first, copy source code after
This allows to reuse the base layer.
> Problem: docker build times

- Dockerfile
Commit 0619cf2612ac9ae5048520ee0c078eef7e96808b made it better already, but precopying requirements.txt prevents the complete pip3 install to execute whenever a file changes.
> Precopy requirements.txt in Dockerfile

- mythril/ether/ethcontract.py
This causes contracts with multiple links to be modified incorrectly.
If there were multiple links then it would see them as one and also remove the bytecode in between.
Fixes #568
However, no reentrancy is reported
> Change regex to limit to correct pattern

- mythril/laser/ethereum/transaction/transaction_models.py
Without this patch there are situations where a contract gets created with no bytecode, which will make other parts of the analysis fail when they try to get an instruction with a certain index
fixes #574
> Also check for empty return data

- mythril/analysis/templates/callgraph.html
- static/Ownable.html
- static/assertions.html
- static/mythril.html
- tests/testdata/outputs_expected/calls.sol.o.graph.html
- tests/testdata/outputs_expected/environments.sol.o.graph.html
- tests/testdata/outputs_expected/ether_send.sol.o.graph.html
- tests/testdata/outputs_expected/exceptions.sol.o.graph.html
- tests/testdata/outputs_expected/kinds_of_calls.sol.o.graph.html
- tests/testdata/outputs_expected/metacoin.sol.o.graph.html
- tests/testdata/outputs_expected/multi_contracts.sol.o.graph.html
- tests/testdata/outputs_expected/nonascii.sol.o.graph.html
- tests/testdata/outputs_expected/origin.sol.o.graph.html
- tests/testdata/outputs_expected/overflow.sol.o.graph.html
- tests/testdata/outputs_expected/returnvalue.sol.o.graph.html
- tests/testdata/outputs_expected/suicide.sol.o.graph.html
- tests/testdata/outputs_expected/underflow.sol.o.graph.html
Fixes https://github.com/ConsenSys/mythril/issues/363.
Sonar no longer reports any missing <!DOCTYPE> or <TITLE> tags.
> Add <!DOCTYPE> and <TITLE> tags

- Dockerfile
Docker build failed after https://github.com/ConsenSys/mythril/pull/585 since the mythril module can't be installed without the source code folder. 
Fixed by separating the pip3 installs from the mythril module installation.
> Fix docker build: Mythril module installation needs source code copied

- mythril/disassembler/disassembly.py
- mythril/ether/ethcontract.py
- mythril/interfaces/cli.py
- mythril/mythril.py
- mythril/support/signatures.py
- requirements.txt
- setup.py
- tests/report_test.py
This PR adds the ethereum-input-decoder python module to the requirements installed with pip and adds an argument -q/--query-signature to enable function signature lookups through www.4byte.directory.
"Fixes" https://github.com/ConsenSys/mythril/issues/590.
> Add query-signature argument, add ethereum-input-decoder to requirements

- mythril/laser/ethereum/svm.py
Typo is error wording:
```
WARNING:root:No contract was created during the execution of contract creation Increase the resources for creation execution (--max-depth or --create_timeout)
```
`--create_timeout` -> `--create-timeout`
> Change error wording

- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_0.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_1.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_2.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_3.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_4.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_5.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_6.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_bigOffset.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_bigOffset2.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_bigSize.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeNoQuadraticCost31.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost32.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost32_zeroSize.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost33.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost63.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost64.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost64_2.json
- tests/laser/evm_testsuite/VMTests/vmSha3Test/sha3_memSizeQuadraticCost65.json
- tests/laser/evm_testsuite/evm_test.py
adds sha3 vm tests
Also regarding the offset, the implementations I have seen like goethereum , aleth, pyethereum all of them seem to follow the same procedure because extending memory till that offset seems to be quite  costly as it's roughly proportional to square of the offset.
> Add sha3 tests

- mythril/laser/ethereum/state.py
StackUnderflowException was being raised even though there were enough elements in the stack.
> Correct the StackUnderflowException

- requirements.txt
- setup.py
Just to triple check, @b-mueller can you confirm that mythril + z3 4.8 discovers the exception:
```solidity
pragma solidity ^0.4.21;
contract TokenSale {
mapping(address => uint256) public balanceOf;
uint256 constant PRICE_PER_TOKEN = 1 ether;
function TokenSale(address _player) public payable {
require(msg.value == 1 ether);
}
function isComplete() public view returns (bool) {
return address(this).balance < 1 ether;
}
function buy(uint256 numTokens) public payable {
require(msg.value == numTokens * PRICE_PER_TOKEN);
assert(!(msg.value == 0 && numTokens > 0));
balanceOf[msg.sender] += numTokens;
}
function sell(uint256 numTokens) public {
require(balanceOf[msg.sender] >= numTokens);
balanceOf[msg.sender] -= numTokens;
msg.sender.transfer(numTokens * PRICE_PER_TOKEN);
}
}
```
> Raise z3 version

- CONTRIBUTING.md
There's a reference to a non-existing Gitter channel. I assume the Discord server has replaced that.
> Change gitter links and references to discord

- mythril/laser/ethereum/instructions.py
Fixes a bug where Mythril would prematurely stop symbolic execution when encountering a SUICIDE instruction.
> Deepcopy account state before deletion on selfdestuct

- mythril/analysis/modules/ether_thief.py
An "ETH relay" contract is often found on the mainnet. This contract contains a function that sends its balance to a fixed address ([example](https://etherscan.io/address/0x94e934139ae32efa180beaecc7e92dbe141de9bd#code)). This PR narrows the win condition by adding the following constraints:
- The receiver address must be is identical to the sender address;
- The sender address can be chosen arbitrarily.
> Introduce additional constraints in Ether Thief module

- .circleci/config.yml
This variables should be added into Circle CI ENV variables:
```
ORGANIZATION 
WEBHOOK_PROJECT
CIRCLE_TOKEN
```
> Configure call to webhook in Circle CI build

- mythril/laser/ethereum/svm.py
Adds:
```
$ myth -x solidity_examples/weak_random.sol -v4
(...)
mythril.laser.ethereum.svm [INFO]: Starting contract creation transaction
mythril.laser.ethereum.svm [INFO]: Finished contract creation, found 1 open states
mythril.laser.ethereum.svm [INFO]: Starting message call transaction, iteration: 0, 1 initial states
mythril.laser.ethereum.svm [INFO]: Number of new instructions covered in tx 0: 529
mythril.laser.ethereum.svm [INFO]: Starting message call transaction, iteration: 1, 162 initial states
```
> Log number of open states at start of tx

- mythril/analysis/modules/base.py
- mythril/analysis/symbolic.py
- mythril/laser/ethereum/svm.py
- mythril/laser/ethereum/transaction/concolic.py
- mythril/laser/ethereum/transaction/symbolic.py
- mythril/mythril.py
- mythril/support/truffle.py
Store nodes only when module with entrypoint="post" should be executed or a html graph statespace needs to be constructed or when statespace has to be dumped. This makes contracts like BECToken.sol executable in the computers of the ordinary people.
> Stores the entire statespace only when necessary

- docs/source/conf.py
This should keep the docs formatting consistent between this and the mythx developer guide.
> Update docs theme to the read the docs theme

- mythril/laser/ethereum/plugins/implementations/coverage/__init__.py
- mythril/laser/ethereum/plugins/implementations/coverage/coverage_plugin.py
- mythril/laser/ethereum/plugins/implementations/coverage/coverage_strategy.py
- mythril/laser/ethereum/strategy/__init__.py
Tries to direct symbolic execution towards yet uncovered instructions
@norhh do you think this could be used to counteract the issues with big contracts that the function entry of some functions might not be reached? (At least in the first transaction) The instruction coverage plugin should be extensible to keep track of coverages in different transactions, which would mitigate the problem over multiple transactions.
> Coverage based search strategy

- mythril/analysis/modules/multiple_sends.py
Changes to multiple_send module:
- Store call offsets instead of call objects in the state annotation (to remove overhead)
- Instead of reporting a single issue listing all calls, create a separate issue for each call that follows a previous call. This results in more usable location information and passes the SWC test case [send_loop.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/solidity/call_best_practices/send_loop/send_loop.sol).
> Refactor multiple_sends module

- mythril/analysis/report.py
some escape characters are visible in jsonv2 due to the formatting, this PR eliminates them.
> Improve reporting for jsonv2

- mythril/laser/ethereum/instructions.py
This just removes the logs or uses hash of symbol over the actual symbol while creating new symbol. This is only done for the bottleneck instructions.
> Speedup bottleneck instructions by removing or hashing the symbols

- mythril/analysis/modules/integer.py
When a tainted symbolic variable is used as call value in a message call add it to the stack of symbolic expressions to be checked for overflows.
Helps detect the third integer overflow in [tokensalechallenge](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/solidity/ctf/tokensalechallenge/tokensalechallenge.sol).
> Consider potential overflows when result is used as call value

- mythril/laser/ethereum/plugins/implementations/dependency_pruner.py
Blocks with a dependency map would be be sometimes pruned if the same block was revisited in a later transaction from a newly discovered path. This would cause viable paths to be pruned if the optimizer used a "common stop" block (block with a STOP instruction re-used by multiple functions). 
With this fix, paths are not pruned if any storage written in the previous transactions have been read during the current iteration instead of only checking against the dependency map.
Also:
- Fix redundant hook on the `JUMPDEST` instruction.
- Fix incorrect appending of addresses to path in `DependencyAnnotation`.
> Fix issues in dependency pruning plugin

- mythril/laser/smt/bitvec.py
> Handle __eq__ and __ne__ for BitVecs with different sizes

- mythril/laser/ethereum/plugins/implementations/dependency_pruner.py
New algorithm:
- this block is encountered for the first time in the current 'thread' ? -> execute
- somewhere along this path are state modifications that have been observed to affect execution -> execute 
- somewhere along this paths are dependencies on state that has been modified in the previous transaction -> execute 
- otherwise -> skip
> Refactor pruning plugin

- mythril/interfaces/cli.py
- mythril/mythril/mythril_disassembler.py
Modified mythril_disassembler.py to add useful suggestion when CompilerError is invoked by a solidity version mismatch.
> Add Useful Suggestion to Solidity Version CompilerErrors

- mythril/analysis/report.py
- mythril/analysis/templates/report_as_markdown.jinja2
- mythril/analysis/templates/report_as_text.jinja2
- mythril/disassembler/disassembly.py
Adds function names to text and markdown reports:
```
$myth analyze token-with-backdoor.sol -t3
==== Exception State ====
SWC ID: 110
Severity: Low
Contract: Token
Function name: test_invariants()
PC address: 621
Estimated Gas Usage: 715 - 1000
A reachable exception has been detected.
It is possible to trigger an exception (opcode 0xfe). Exceptions can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. Note that explicit `assert()` should only be used to check invariants. Use `require()` for regular input checking.
--------------------
In file: token-with-backdoor.sol:28
assert(balances[msg.sender] <= 1000)
--------------------
Transaction Sequence:
Caller: [CREATOR], data: [CONTRACT CREATION], value: 0x0
Caller: [CREATOR], function: airdrop(), …
```
> Add function names to report output

- mythril/interfaces/cli.py
Hi !
First PR, I may not have done everything correctly. (Should I push to develop instead of master?)
Also I was not able to pass the full test suite (some truffle problems finding the right solc compiler…), but most tests passed, and the one that failed should be unrelated.
This is an opinionated choice that would change the default behavior of Mythril. I'm happy to make it an additional parameter to control only contract loading, if you prefer.
What I want is to be able to enable contract loading from the CLI, which is impossible now.
I kept the old parameter name so nothing breaks. It could be deprecated/removed at some point.
> Load contracts from the blockchain by default

- mythril/support/loader.py
Also refactor the loader quite a bit:
- remove the cache dictionary, and use functools.lru_cache instead
- also use lru_cache for caching contract code
- add type annotations, now mypy would be complaining if we didn't
check "self.eth" for None.
- use log.debug() with %s, it's good pratice and allow advanced logging
to group by log messages / parameters if needed.
Let me know if you prefer to split the refactoring part with the part where I check that "eth" is None.
>  Fix bug #1168 by checking eth is not None in the loader. Refactor the loader.

- mythril/analysis/templates/report_as_markdown.jinja2
- mythril/analysis/templates/report_as_text.jinja2
Updated jinja templates to reflect initialStates of transaction sequences. Should 'code' also be included as part of the initial state?
> Print initial state in jinja

- mythril/analysis/solver.py
We currently don't correctly model tx.origin and tx.caller, so this is a hack to make sure balances do not overflow.
Constrain all transaction callers to have <= 1000 ETH
> Fix balance overflow

- mythril/laser/ethereum/state/account.py
This should be the right fix for #1176 that does not introduce a regression (see #674 for a regression example)
Please triple check this code, I still don't know how to run integrations tests properly, and I feel like the default test suite is pretty "light" (it didn't catch a few errors I made). I tested on a few contracts but that's all.
> Fix for #1176: track what storage has been initialized. Load uninitialized storage once.

- mythril/__version__.py
- mythril/ethereum/util.py
- mythril/mythril/mythril_disassembler.py
- requirements.txt
- setup.py
- tests/native_test.py
- tests/native_tests.sol
- tox.ini
Mythril relies on `py-solc` to install versions specified by the `--solv` parameter. Unfortunately, `py-solc` does not seem maintained and cannot install solc with versions 0.5.x. Thus, Mythril currently supports only the system solc installation for 0.5.x. 
This PR adds `py-solc-x` dependency which is used for versions other than 0.4.x. For 0.4.x, handling by `py-solc` is preserved, because `py-solc-x` declares incompatibility of 0.4.x installations with OSX.
This should solve Mythril's dynamic support for 0.5.x that is reference e.g. in ethereum/py-solc#63, andindirectly also in #1217.
Tested with Docker as follows:
```
docker build .
docker run -v /tmp:/tmp 3ff13f1e1c8b analyze /tmp/contract.sol --solv 0.5.10 -o jsonv2
docker run -v /tmp:/tmp 3ff13f1e1c8b analyze /tmp/contract.sol …
```
> Added support for solidity 0.5.x

- mythril/laser/ethereum/instructions.py
When arguments to SIGNEXTEND are symbolic, a type error is thrown but no global_state is returned.
> Added returning global state to SIGNEXTEND opcode.

- mythril/laser/ethereum/state/machine_state.py
- mythril/laser/ethereum/strategy/extensions/bounded_loops.py
Previously, function calls were falsely considered as loops. This PR fixes this issue by considering the 'context' of the call. If a jumpdest was reached by a different instruction, it would not add to its loop annotation.
> Added 'context' to loop annotations.

- mythril/analysis/module/base.py
- mythril/analysis/module/loader.py
- mythril/analysis/module/modules/arbitrary_jump.py
- mythril/analysis/module/modules/arbitrary_write.py
- mythril/analysis/module/modules/delegatecall.py
- mythril/analysis/module/modules/dependence_on_predictable_vars.py
- mythril/analysis/module/modules/deprecated_ops.py
- mythril/analysis/module/modules/ether_thief.py
- mythril/analysis/module/modules/exceptions.py
- mythril/analysis/module/modules/external_calls.py
- mythril/analysis/module/modules/integer.py
- mythril/analysis/module/modules/multiple_sends.py
- mythril/analysis/module/modules/state_change_external_calls.py
- mythril/analysis/module/modules/suicide.py
- mythril/analysis/module/modules/unchecked_retval.py
- mythril/analysis/module/modules/user_assertions.py
- mythril/exceptions.py
- mythril/interfaces/cli.py
- mythril/laser/ethereum/keccak_function_manager.py
- mythril/mythril/mythril_analyzer.py
I refactored the class names and "name" fields of each module for consistency and added the following:
1. Users can now select modules by classname:
```
$ myth analyze test.sol -mIntegerArithmetics,Exceptions
```
2. Adding a non-existent module throws an error:
```
$ myth analyze test.sol -mIntegerArithmetics,Exceptions,Lol
mythril.interfaces.cli [ERROR]: Invalid detection module: Lol 
```
3. The new command "list-detectors" provides a list of the available modules:
```
$ myth list-detectors
ArbitraryJump: Jump to an arbitrary bytecode location
ArbitraryStorage: Write to an arbitrary storage location
ArbitraryDelegateCall: Delegatecall to a user-specified address
PredictableVariables: Control flow depends on a predictable environment variable
DeprecatedOperations: Usage of deprecated …
```
> Modules selection usability overhaul

- mythril/analysis/symbolic.py
- mythril/ethereum/interface/rpc/client.py
- mythril/interfaces/cli.py
- mythril/laser/ethereum/state/account.py
- mythril/support/loader.py
- Adds new function `read_balance(address` to dynloader
- Account constructor now reads intial account balance from blockchain if dynloader is available
- Minor: Don't pass dynloader to `CREATOR_ACCOUNT` and `ATTACKER_ACCOUNT` which are virtual
- Use a single boolean / flag to determine if data should be loaded instead of separating code/storage/balances:
```
--no-onchain-data. Don't attempt to retrieve contract code, variables and balances from the blockchain
```
> Load intial account balances from blockchain and refactor loader flags

- mythril/analysis/module/modules/ether_thief.py
- mythril/laser/ethereum/plugins/implementations/mutation_pruner.py
- mythril/laser/ethereum/transaction/symbolic.py
- Revert to hooking `CALL` and `STATICCALL` in EtherThief module
- Prevent`MutationPruner` from pruning paths that where ETH could have been received via msg.value
**TESTS**
**No payable functions:**
```
pragma solidity ^0.5.0;
contract SimpleEtherDrain {
function withdrawAllAnyone() public {
msg.sender.transfer(address(this).balance);
}
}
```
```
$ $MYTH a SimpleEtherDrain.sol -mEtherThief
The analysis was completed successfully. No issues were detected.
```
**Payable constructor:**
```
pragma solidity ^0.5.0;
contract SimpleEtherDrain {
constructor() public payable {
}
function withdrawAllAnyone() public {
msg.sender.transfer(address(this).balance);
}
}
```
```
$ $MYTH a SimpleEtherDrain.sol -mEtherThief -t1
==== Unprotected Ether Withdrawal ====
SWC ID: 105
Severity: High
Contract: …
```
> Simplify EtherThief and fix pruning behaviour

- mythril/analysis/module/modules/delegatecall.py
- mythril/analysis/module/modules/external_calls.py
Change call checks to warn only if a the sender can trigger a call with unrestricted gas to an arbitrary address.
> Only warn about calls to user-supplied addresses

- mythril/analysis/module/modules/user_assertions.py
- mythril/laser/ethereum/state/constraints.py
As a user I want violations of user assertions to always be reported even if the transaction reverts. This PR changes the UserAssertion module to add an issue instead of a `PotentialIssue` when a violation is encountered.
Also, black reformatted something in constraints.py :)
> Always report user assertions

- mythril/ethereum/util.py
- requirements.txt
While re-configuring my python dev environment I had some issues with the version of py-solc-x that we were using.
I've updated the version to the most recent `0.10.0` and fixed up some of the code that would interact with the solc x installed binaries.
This now uses the function `get_executable` rather than trying to find the compiler binary manually.
> Update solcx version

- mythril/laser/plugin/builder.py
- mythril/laser/plugin/loader.py
- mythril/laser/plugin/plugins/benchmark.py
- mythril/laser/plugin/plugins/call_depth_limiter.py
- mythril/laser/plugin/plugins/coverage/coverage_plugin.py
- mythril/laser/plugin/plugins/dependency_pruner.py
- mythril/laser/plugin/plugins/instruction_profiler.py
- mythril/laser/plugin/plugins/mutation_pruner.py
For some plugins classes `plugin_name` was used, for others `name` was used and it's confusing
> Change plugin_name to name

- mythril/laser/ethereum/state/world_state.py
Noticed that when my contract had a "0x0ABCD..." dependency, Mythril sent the eth_getBalance request to my RPC with address "0xABCD.." instead.
Naturally, my RPC returned an error. Ultimately, there is an error somewhere between converting integers to strings, that loses leading zeros on addresses.
This patch fixes this bug, and further simplifies the two cases of isinstance(addr, int) and isinstance(addr, str) by merging them. Less duplicated code, less bugs.
> Bugfix for lost leading zeros in address, refactor

- mythril/analysis/potential_issues.py
In the original code, Mythril removes the potential_issue in the loop.
However, in Python, during a loop of a list, removing an item will make things go wrong.
Talk is cheap, lets try the following code:
```python
myList = [1,2,3,4,5,6]
for i in myList:
print(i)
myList.remove(i)
```
It only prints (1,3,5), and (2,4,6) remains.
The same things go wrong in Mythril, as it just skip some potential issues.
For example, if the len(potential_issues) is 10, it might just check 6 SMT of them.
In Mythril's funciton, after checking a potential_issue, I think there is no need to remove it from the list.
Hence, deleting the ```remove``` code should work for this bug.
> Fix bug during checking potential issues

- mythril/support/loader.py
- requirements.txt
- setup.py
Some clients return "0x" instead of "0x0" #1546
> Handle an edgecase from local host clients

- mythril/analysis/module/modules/integer.py
- requirements.txt
Fix py-evm version and restrict others. py-evm can only be fixed since their versions are non-numerical due to it being in alpha.
> Fix py-evm version

- mythril/laser/smt/solver/solver.py
When using mythril as a library and applying it to multiple inputs within the same process instance this issue eventually leads to the following exception:
```
CRITICAL:mythril.mythril.mythril_analyzer:Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
File "/Users/izeigerman/github/eth-explorer/.venv/lib/python3.9/site-packages/mythril/mythril/mythril_analyzer.py", line 149, in fire_lasers
sym = SymExecWrapper(
File "/Users/izeigerman/github/eth-explorer/.venv/lib/python3.9/site-packages/mythril/analysis/symbolic.py", line 214, in __init__
self.laser.sym_exec(world_state=world_state, target_address=address.value)
File "/Users/izeigerman/github/eth-explorer/.venv/lib/python3.9/site-packages/mythril/laser/ethereum/s …
```
> Fix the leaking file descriptor when returning a z3 smt check result

- docs/source/module-list.rst
The links to the modules on the [Analysis Modules page](https://mythril-classic.readthedocs.io/en/master/analysis-modules.html) of the documentation used an old file structure with 'analysis/modules/..." instead of "analysis/module/modules/..."
> Fixed broken links in Analysis Modules of documentation

- mythril/laser/ethereum/instructions.py
fixes #1627.
For some reason, we were updating depth for jump instruction.
> remove depth for jump

- docs/source/module-list.rst
External Calls mentioned *SWC-117* but links (corrrectly) to SWC-107, fixed typo to *SWC-107*
> Typo: External Calls now states correctly SWC-107

- mythril/support/support_utils.py
- requirements.txt
- tox.ini
Switch to py-evm libraries. Wait out for newly released versions of blake2b-py for python 3.10,  since reimplementing them is hard.
> Support py36 through py39

- mythril/analysis/module/modules/arbitrary_jump.py
- tests/analysis_tests/arbitrary_jump_test.py
For some contracts with ecdsa such as
```
function verifySignatures(bytes32 hash, Structs.Signature[] memory signatures, Structs.GuardianSet memory guardianSet) public pure returns (bool valid, string memory reason) {
uint8 lastIndex = 0;
for (uint i = 0; i < signatures.length; i++) {
Structs.Signature memory sig = signatures[i];
require(i == 0 || sig.guardianIndex > lastIndex, "signature indices must be ascending");
lastIndex = sig.guardianIndex;
if(ecrecover(hash, sig.v, sig.r, sig.s) != guardianSet.keys[sig.guardianIndex]){
return (false, "VM signature invalid");
}
}
```
The jumpdest points to calldata of the function which is `verifySignatures`, such cases can be avoided by solving for jumpdest.
> Fix issues with arbitrary jump dest

- tox.ini
Since `geth` gets killed by CI after some time, it is better to run only the necessary python versions.
> Remove additional python runs in tox
